-- Generated from src/lib/seed-menu.ts. Do not edit by hand; run `pnpm seed:sql`.

insert into public.menu_categories (id, slug, name, tagline, sort_order, active) values ('cat-small-plates', 'small-plates', 'Small Plates', 'Boarding snacks. Built to share.', 1, true)
  on conflict (id) do update set name = excluded.name, tagline = excluded.tagline, sort_order = excluded.sort_order;
insert into public.menu_categories (id, slug, name, tagline, sort_order, active) values ('cat-wings', 'wings', 'Wings', 'Bold flavor. Saucy & irresistible.', 2, true)
  on conflict (id) do update set name = excluded.name, tagline = excluded.tagline, sort_order = excluded.sort_order;
insert into public.menu_categories (id, slug, name, tagline, sort_order, active) values ('cat-sushi', 'sushi', 'Sushi & Rolls', 'Hand-rolled, island-fresh.', 3, true)
  on conflict (id) do update set name = excluded.name, tagline = excluded.tagline, sort_order = excluded.sort_order;
insert into public.menu_categories (id, slug, name, tagline, sort_order, active) values ('cat-bowls', 'bowls', 'Poke & Bowls', 'Fresh, colourful, made for your cravings.', 4, true)
  on conflict (id) do update set name = excluded.name, tagline = excluded.tagline, sort_order = excluded.sort_order;
insert into public.menu_categories (id, slug, name, tagline, sort_order, active) values ('cat-noodles', 'noodles', 'Noodles & Ramen', 'The bowl on our logo.', 5, true)
  on conflict (id) do update set name = excluded.name, tagline = excluded.tagline, sort_order = excluded.sort_order;
insert into public.menu_categories (id, slug, name, tagline, sort_order, active) values ('cat-mains', 'mains', 'Rice & Mains', 'Where Asia meets the Caribbean.', 6, true)
  on conflict (id) do update set name = excluded.name, tagline = excluded.tagline, sort_order = excluded.sort_order;
insert into public.menu_categories (id, slug, name, tagline, sort_order, active) values ('cat-sides', 'sides', 'Sides', null, 7, true)
  on conflict (id) do update set name = excluded.name, tagline = excluded.tagline, sort_order = excluded.sort_order;
insert into public.menu_categories (id, slug, name, tagline, sort_order, active) values ('cat-drinks', 'drinks', 'Drinks & Cocktails', 'First class, every day.', 8, true)
  on conflict (id) do update set name = excluded.name, tagline = excluded.tagline, sort_order = excluded.sort_order;

insert into public.menu_items (id, category_id, slug, name, description, price_cents, image_url, tags, options, available, featured, sort_order) values ('item-jerk-chicken-gyoza', 'cat-small-plates', 'jerk-chicken-gyoza', 'Jerk Chicken Gyoza', 'Six pan-seared dumplings, jerk-spiced chicken, scallion, ponzu dip.', 1200, null, '{"popular","spicy"}', '[]'::jsonb, true, false, 1)
  on conflict (id) do update set name = excluded.name, description = excluded.description, price_cents = excluded.price_cents, image_url = excluded.image_url, tags = excluded.tags, options = excluded.options, featured = excluded.featured, sort_order = excluded.sort_order;
insert into public.menu_items (id, category_id, slug, name, description, price_cents, image_url, tags, options, available, featured, sort_order) values ('item-coconut-shrimp-tempura', 'cat-small-plates', 'coconut-shrimp-tempura', 'Coconut Shrimp Tempura', 'Crispy coconut batter, sweet chili mango sauce.', 1400, null, '{"popular"}', '[]'::jsonb, true, false, 2)
  on conflict (id) do update set name = excluded.name, description = excluded.description, price_cents = excluded.price_cents, image_url = excluded.image_url, tags = excluded.tags, options = excluded.options, featured = excluded.featured, sort_order = excluded.sort_order;
insert into public.menu_items (id, category_id, slug, name, description, price_cents, image_url, tags, options, available, featured, sort_order) values ('item-saltfish-spring-rolls', 'cat-small-plates', 'saltfish-spring-rolls', 'Saltfish Spring Rolls', 'Anguillian saltfish, peppers and onion in a crackly wrapper, tamarind dip.', 1100, null, '{}', '[]'::jsonb, true, false, 3)
  on conflict (id) do update set name = excluded.name, description = excluded.description, price_cents = excluded.price_cents, image_url = excluded.image_url, tags = excluded.tags, options = excluded.options, featured = excluded.featured, sort_order = excluded.sort_order;
insert into public.menu_items (id, category_id, slug, name, description, price_cents, image_url, tags, options, available, featured, sort_order) values ('item-jerk-pork-belly-bao', 'cat-small-plates', 'jerk-pork-belly-bao', 'Jerk Pork Belly Bao', 'Two fluffy buns, sticky jerk pork belly, pickled cucumber, hoisin.', 1300, null, '{"spicy"}', '[]'::jsonb, true, false, 4)
  on conflict (id) do update set name = excluded.name, description = excluded.description, price_cents = excluded.price_cents, image_url = excluded.image_url, tags = excluded.tags, options = excluded.options, featured = excluded.featured, sort_order = excluded.sort_order;
insert into public.menu_items (id, category_id, slug, name, description, price_cents, image_url, tags, options, available, featured, sort_order) values ('item-chili-salt-edamame', 'cat-small-plates', 'chili-salt-edamame', 'Chili-Salt Edamame', 'Steamed edamame, sea salt, chili flakes, lime.', 700, null, '{"veg","gf"}', '[]'::jsonb, true, false, 5)
  on conflict (id) do update set name = excluded.name, description = excluded.description, price_cents = excluded.price_cents, image_url = excluded.image_url, tags = excluded.tags, options = excluded.options, featured = excluded.featured, sort_order = excluded.sort_order;
insert into public.menu_items (id, category_id, slug, name, description, price_cents, image_url, tags, options, available, featured, sort_order) values ('item-miso-plantain-bites', 'cat-small-plates', 'miso-plantain-bites', 'Miso-Glazed Plantain Bites', 'Caramelised sweet plantain, miso butter, toasted sesame.', 900, null, '{"veg"}', '[]'::jsonb, true, false, 6)
  on conflict (id) do update set name = excluded.name, description = excluded.description, price_cents = excluded.price_cents, image_url = excluded.image_url, tags = excluded.tags, options = excluded.options, featured = excluded.featured, sort_order = excluded.sort_order;
insert into public.menu_items (id, category_id, slug, name, description, price_cents, image_url, tags, options, available, featured, sort_order) values ('item-route-86-wings-6', 'cat-wings', 'route-86-wings-6', 'Route 86 Wings · 6 pc', 'Twice-fried, tossed in your sauce, sesame and scallion. $1 a piece on Wingman Wednesday (applied in store).', 1200, '/menu/wings.jpg', '{"popular"}', '[{"id":"sauce","name":"Sauce","required":true,"type":"single","choices":[{"id":"sweet-chili-jerk","name":"Sweet Chili Jerk"},{"id":"gochujang-bbq","name":"Gochujang BBQ"},{"id":"honey-soy-garlic","name":"Honey Soy Garlic"},{"id":"scotch-bonnet-buffalo","name":"Scotch Bonnet Buffalo 🔥"}]}]'::jsonb, true, true, 7)
  on conflict (id) do update set name = excluded.name, description = excluded.description, price_cents = excluded.price_cents, image_url = excluded.image_url, tags = excluded.tags, options = excluded.options, featured = excluded.featured, sort_order = excluded.sort_order;
insert into public.menu_items (id, category_id, slug, name, description, price_cents, image_url, tags, options, available, featured, sort_order) values ('item-route-86-wings-12', 'cat-wings', 'route-86-wings-12', 'Route 86 Wings · 12 pc', 'Bring a wingman. Twelve wings, pick one sauce or split two.', 2200, '/menu/wings.jpg', '{}', '[{"id":"sauce","name":"Sauce","required":true,"type":"single","choices":[{"id":"sweet-chili-jerk","name":"Sweet Chili Jerk"},{"id":"gochujang-bbq","name":"Gochujang BBQ"},{"id":"honey-soy-garlic","name":"Honey Soy Garlic"},{"id":"scotch-bonnet-buffalo","name":"Scotch Bonnet Buffalo 🔥"}]}]'::jsonb, true, false, 8)
  on conflict (id) do update set name = excluded.name, description = excluded.description, price_cents = excluded.price_cents, image_url = excluded.image_url, tags = excluded.tags, options = excluded.options, featured = excluded.featured, sort_order = excluded.sort_order;
insert into public.menu_items (id, category_id, slug, name, description, price_cents, image_url, tags, options, available, featured, sort_order) values ('item-dragon-roll', 'cat-sushi', 'dragon-roll', 'Dragon Roll', 'Eel, cucumber, avocado on top, eel sauce, sesame, scallion.', 1800, '/menu/sushi.jpg', '{"popular"}', '[]'::jsonb, true, true, 9)
  on conflict (id) do update set name = excluded.name, description = excluded.description, price_cents = excluded.price_cents, image_url = excluded.image_url, tags = excluded.tags, options = excluded.options, featured = excluded.featured, sort_order = excluded.sort_order;
insert into public.menu_items (id, category_id, slug, name, description, price_cents, image_url, tags, options, available, featured, sort_order) values ('item-island-spicy-tuna-roll', 'cat-sushi', 'island-spicy-tuna-roll', 'Island Spicy Tuna Roll', 'Spicy tuna, cucumber, scotch bonnet aioli, crispy shallot.', 1600, null, '{"spicy"}', '[]'::jsonb, true, false, 10)
  on conflict (id) do update set name = excluded.name, description = excluded.description, price_cents = excluded.price_cents, image_url = excluded.image_url, tags = excluded.tags, options = excluded.options, featured = excluded.featured, sort_order = excluded.sort_order;
insert into public.menu_items (id, category_id, slug, name, description, price_cents, image_url, tags, options, available, featured, sort_order) values ('item-crunchy-mango-shrimp-roll', 'cat-sushi', 'crunchy-mango-shrimp-roll', 'Crunchy Mango Shrimp Roll', 'Tempura shrimp, mango, avocado, tempura crunch, sweet chili drizzle.', 1700, null, '{}', '[]'::jsonb, true, false, 11)
  on conflict (id) do update set name = excluded.name, description = excluded.description, price_cents = excluded.price_cents, image_url = excluded.image_url, tags = excluded.tags, options = excluded.options, featured = excluded.featured, sort_order = excluded.sort_order;
insert into public.menu_items (id, category_id, slug, name, description, price_cents, image_url, tags, options, available, featured, sort_order) values ('item-salmon-avocado-roll', 'cat-sushi', 'salmon-avocado-roll', 'Salmon Avocado Roll', 'Fresh salmon, avocado, sesame.', 1500, null, '{}', '[]'::jsonb, true, false, 12)
  on conflict (id) do update set name = excluded.name, description = excluded.description, price_cents = excluded.price_cents, image_url = excluded.image_url, tags = excluded.tags, options = excluded.options, featured = excluded.featured, sort_order = excluded.sort_order;
insert into public.menu_items (id, category_id, slug, name, description, price_cents, image_url, tags, options, available, featured, sort_order) values ('item-veggie-rainbow-roll', 'cat-sushi', 'veggie-rainbow-roll', 'Veggie Rainbow Roll', 'Avocado, cucumber, mango, carrot, pickled radish.', 1300, null, '{"veg"}', '[]'::jsonb, true, false, 13)
  on conflict (id) do update set name = excluded.name, description = excluded.description, price_cents = excluded.price_cents, image_url = excluded.image_url, tags = excluded.tags, options = excluded.options, featured = excluded.featured, sort_order = excluded.sort_order;
insert into public.menu_items (id, category_id, slug, name, description, price_cents, image_url, tags, options, available, featured, sort_order) values ('item-sushi-platter-16', 'cat-sushi', 'sushi-platter-16', 'Sushi Platter · 16 pc', 'Chef''s choice of four rolls. Perfect for two.', 3200, null, '{}', '[]'::jsonb, true, false, 14)
  on conflict (id) do update set name = excluded.name, description = excluded.description, price_cents = excluded.price_cents, image_url = excluded.image_url, tags = excluded.tags, options = excluded.options, featured = excluded.featured, sort_order = excluded.sort_order;
insert into public.menu_items (id, category_id, slug, name, description, price_cents, image_url, tags, options, available, featured, sort_order) values ('item-ahi-tuna-poke-bowl', 'cat-bowls', 'ahi-tuna-poke-bowl', 'Ahi Tuna Poke Bowl', 'Marinated ahi tuna, edamame, seaweed salad, mango, avocado, cucumber, carrot, furikake, spicy mayo.', 1900, '/menu/poke.jpg', '{"popular","gf"}', '[{"id":"base","name":"Base","required":true,"type":"single","choices":[{"id":"sushi-rice","name":"Sushi rice"},{"id":"brown-rice","name":"Brown rice"},{"id":"mixed-greens","name":"Mixed greens"}]},{"id":"extras","name":"Extras","type":"multi","choices":[{"id":"avocado","name":"Extra avocado","priceDeltaCents":200},{"id":"egg","name":"Soft egg","priceDeltaCents":150},{"id":"plantain","name":"Sweet plantain","priceDeltaCents":200}]}]'::jsonb, true, true, 15)
  on conflict (id) do update set name = excluded.name, description = excluded.description, price_cents = excluded.price_cents, image_url = excluded.image_url, tags = excluded.tags, options = excluded.options, featured = excluded.featured, sort_order = excluded.sort_order;
insert into public.menu_items (id, category_id, slug, name, description, price_cents, image_url, tags, options, available, featured, sort_order) values ('item-salmon-poke-bowl', 'cat-bowls', 'salmon-poke-bowl', 'Salmon Poke Bowl', 'Salmon, edamame, seaweed, mango, avocado, ponzu, sesame.', 1900, null, '{"gf"}', '[{"id":"base","name":"Base","required":true,"type":"single","choices":[{"id":"sushi-rice","name":"Sushi rice"},{"id":"brown-rice","name":"Brown rice"},{"id":"mixed-greens","name":"Mixed greens"}]},{"id":"extras","name":"Extras","type":"multi","choices":[{"id":"avocado","name":"Extra avocado","priceDeltaCents":200},{"id":"egg","name":"Soft egg","priceDeltaCents":150},{"id":"plantain","name":"Sweet plantain","priceDeltaCents":200}]}]'::jsonb, true, false, 16)
  on conflict (id) do update set name = excluded.name, description = excluded.description, price_cents = excluded.price_cents, image_url = excluded.image_url, tags = excluded.tags, options = excluded.options, featured = excluded.featured, sort_order = excluded.sort_order;
insert into public.menu_items (id, category_id, slug, name, description, price_cents, image_url, tags, options, available, featured, sort_order) values ('item-jerk-chicken-bowl', 'cat-bowls', 'jerk-chicken-bowl', 'Jerk Chicken Bowl', 'Grilled jerk chicken, pineapple salsa, slaw, plantain, coconut rice.', 1700, null, '{"spicy"}', '[{"id":"base","name":"Base","required":true,"type":"single","choices":[{"id":"sushi-rice","name":"Sushi rice"},{"id":"brown-rice","name":"Brown rice"},{"id":"mixed-greens","name":"Mixed greens"}]},{"id":"extras","name":"Extras","type":"multi","choices":[{"id":"avocado","name":"Extra avocado","priceDeltaCents":200},{"id":"egg","name":"Soft egg","priceDeltaCents":150},{"id":"plantain","name":"Sweet plantain","priceDeltaCents":200}]}]'::jsonb, true, false, 17)
  on conflict (id) do update set name = excluded.name, description = excluded.description, price_cents = excluded.price_cents, image_url = excluded.image_url, tags = excluded.tags, options = excluded.options, featured = excluded.featured, sort_order = excluded.sort_order;
insert into public.menu_items (id, category_id, slug, name, description, price_cents, image_url, tags, options, available, featured, sort_order) values ('item-tofu-teriyaki-bowl', 'cat-bowls', 'tofu-teriyaki-bowl', 'Tofu Teriyaki Bowl', 'Crispy tofu, teriyaki glaze, broccoli, carrot, sesame.', 1500, null, '{"veg"}', '[{"id":"base","name":"Base","required":true,"type":"single","choices":[{"id":"sushi-rice","name":"Sushi rice"},{"id":"brown-rice","name":"Brown rice"},{"id":"mixed-greens","name":"Mixed greens"}]},{"id":"extras","name":"Extras","type":"multi","choices":[{"id":"avocado","name":"Extra avocado","priceDeltaCents":200},{"id":"egg","name":"Soft egg","priceDeltaCents":150},{"id":"plantain","name":"Sweet plantain","priceDeltaCents":200}]}]'::jsonb, true, false, 18)
  on conflict (id) do update set name = excluded.name, description = excluded.description, price_cents = excluded.price_cents, image_url = excluded.image_url, tags = excluded.tags, options = excluded.options, featured = excluded.featured, sort_order = excluded.sort_order;
insert into public.menu_items (id, category_id, slug, name, description, price_cents, image_url, tags, options, available, featured, sort_order) values ('item-route-86-ramen', 'cat-noodles', 'route-86-ramen', 'Route 86 Ramen', 'Rich pork broth, chashu, soft egg, corn, scallion, nori. The bowl on our sign.', 1800, null, '{"popular"}', '[{"id":"spice","name":"Spice level","type":"single","choices":[{"id":"mild","name":"Mild"},{"id":"medium","name":"Medium"},{"id":"hot","name":"Island hot 🌶️"}]}]'::jsonb, true, true, 19)
  on conflict (id) do update set name = excluded.name, description = excluded.description, price_cents = excluded.price_cents, image_url = excluded.image_url, tags = excluded.tags, options = excluded.options, featured = excluded.featured, sort_order = excluded.sort_order;
insert into public.menu_items (id, category_id, slug, name, description, price_cents, image_url, tags, options, available, featured, sort_order) values ('item-curry-goat-ramen', 'cat-noodles', 'curry-goat-ramen', 'Curry Goat Ramen', 'Slow-braised Caribbean curry goat over ramen noodles, scotch bonnet oil, scallion.', 2100, null, '{"spicy","signature"}', '[{"id":"spice","name":"Spice level","type":"single","choices":[{"id":"mild","name":"Mild"},{"id":"medium","name":"Medium"},{"id":"hot","name":"Island hot 🌶️"}]}]'::jsonb, true, true, 20)
  on conflict (id) do update set name = excluded.name, description = excluded.description, price_cents = excluded.price_cents, image_url = excluded.image_url, tags = excluded.tags, options = excluded.options, featured = excluded.featured, sort_order = excluded.sort_order;
insert into public.menu_items (id, category_id, slug, name, description, price_cents, image_url, tags, options, available, featured, sort_order) values ('item-coconut-curry-shrimp-udon', 'cat-noodles', 'coconut-curry-shrimp-udon', 'Coconut Curry Shrimp Udon', 'Thick udon, coconut curry broth, shrimp, bok choy, lime.', 2000, null, '{}', '[{"id":"spice","name":"Spice level","type":"single","choices":[{"id":"mild","name":"Mild"},{"id":"medium","name":"Medium"},{"id":"hot","name":"Island hot 🌶️"}]}]'::jsonb, true, false, 21)
  on conflict (id) do update set name = excluded.name, description = excluded.description, price_cents = excluded.price_cents, image_url = excluded.image_url, tags = excluded.tags, options = excluded.options, featured = excluded.featured, sort_order = excluded.sort_order;
insert into public.menu_items (id, category_id, slug, name, description, price_cents, image_url, tags, options, available, featured, sort_order) values ('item-lobster-garlic-butter-lo-mein', 'cat-noodles', 'lobster-garlic-butter-lo-mein', 'Anguilla Lobster Lo Mein', 'Local lobster, garlic butter, egg noodles, peppers, scallion. Market availability.', 3400, null, '{"signature"}', '[]'::jsonb, true, false, 22)
  on conflict (id) do update set name = excluded.name, description = excluded.description, price_cents = excluded.price_cents, image_url = excluded.image_url, tags = excluded.tags, options = excluded.options, featured = excluded.featured, sort_order = excluded.sort_order;
insert into public.menu_items (id, category_id, slug, name, description, price_cents, image_url, tags, options, available, featured, sort_order) values ('item-veggie-yaki-soba', 'cat-noodles', 'veggie-yaki-soba', 'Veggie Yaki Soba', 'Stir-fried soba, cabbage, carrot, mushroom, sweet soy.', 1400, null, '{"veg"}', '[]'::jsonb, true, false, 23)
  on conflict (id) do update set name = excluded.name, description = excluded.description, price_cents = excluded.price_cents, image_url = excluded.image_url, tags = excluded.tags, options = excluded.options, featured = excluded.featured, sort_order = excluded.sort_order;
insert into public.menu_items (id, category_id, slug, name, description, price_cents, image_url, tags, options, available, featured, sort_order) values ('item-house-fried-rice', 'cat-mains', 'house-fried-rice', 'House Fried Rice', 'Wok-tossed jasmine rice, egg, peppers, scallion, sesame. Pick your protein.', 1300, '/menu/fried_rice.jpg', '{"popular"}', '[{"id":"protein","name":"Protein","required":true,"type":"single","choices":[{"id":"veg","name":"Vegetable"},{"id":"chicken","name":"Chicken","priceDeltaCents":200},{"id":"shrimp","name":"Shrimp","priceDeltaCents":400}]},{"id":"spice","name":"Spice level","type":"single","choices":[{"id":"mild","name":"Mild"},{"id":"medium","name":"Medium"},{"id":"hot","name":"Island hot 🌶️"}]}]'::jsonb, true, true, 24)
  on conflict (id) do update set name = excluded.name, description = excluded.description, price_cents = excluded.price_cents, image_url = excluded.image_url, tags = excluded.tags, options = excluded.options, featured = excluded.featured, sort_order = excluded.sort_order;
insert into public.menu_items (id, category_id, slug, name, description, price_cents, image_url, tags, options, available, featured, sort_order) values ('item-oxtail-fried-rice', 'cat-mains', 'oxtail-fried-rice', 'Oxtail Fried Rice', 'Braised oxtail, butter beans, wok rice, thyme, scallion.', 2400, null, '{"signature"}', '[]'::jsonb, true, false, 25)
  on conflict (id) do update set name = excluded.name, description = excluded.description, price_cents = excluded.price_cents, image_url = excluded.image_url, tags = excluded.tags, options = excluded.options, featured = excluded.featured, sort_order = excluded.sort_order;
insert into public.menu_items (id, category_id, slug, name, description, price_cents, image_url, tags, options, available, featured, sort_order) values ('item-crispy-snapper-sweet-chili', 'cat-mains', 'crispy-snapper-sweet-chili', 'Crispy Snapper, Sweet Chili', 'Whole-fried local snapper, sweet chili glaze, rice and peas, slaw.', 2600, null, '{"gf"}', '[]'::jsonb, true, false, 26)
  on conflict (id) do update set name = excluded.name, description = excluded.description, price_cents = excluded.price_cents, image_url = excluded.image_url, tags = excluded.tags, options = excluded.options, featured = excluded.featured, sort_order = excluded.sort_order;
insert into public.menu_items (id, category_id, slug, name, description, price_cents, image_url, tags, options, available, featured, sort_order) values ('item-teriyaki-salmon', 'cat-mains', 'teriyaki-salmon', 'Teriyaki Salmon', 'Glazed salmon fillet, jasmine rice, sesame greens.', 2400, null, '{}', '[]'::jsonb, true, false, 27)
  on conflict (id) do update set name = excluded.name, description = excluded.description, price_cents = excluded.price_cents, image_url = excluded.image_url, tags = excluded.tags, options = excluded.options, featured = excluded.featured, sort_order = excluded.sort_order;
insert into public.menu_items (id, category_id, slug, name, description, price_cents, image_url, tags, options, available, featured, sort_order) values ('item-jasmine-rice', 'cat-sides', 'jasmine-rice', 'Jasmine Rice', null, 400, null, '{"veg","gf"}', '[]'::jsonb, true, false, 28)
  on conflict (id) do update set name = excluded.name, description = excluded.description, price_cents = excluded.price_cents, image_url = excluded.image_url, tags = excluded.tags, options = excluded.options, featured = excluded.featured, sort_order = excluded.sort_order;
insert into public.menu_items (id, category_id, slug, name, description, price_cents, image_url, tags, options, available, featured, sort_order) values ('item-rice-and-peas', 'cat-sides', 'rice-and-peas', 'Rice & Peas', 'Coconut, thyme, pigeon peas.', 500, null, '{"veg","gf"}', '[]'::jsonb, true, false, 29)
  on conflict (id) do update set name = excluded.name, description = excluded.description, price_cents = excluded.price_cents, image_url = excluded.image_url, tags = excluded.tags, options = excluded.options, featured = excluded.featured, sort_order = excluded.sort_order;
insert into public.menu_items (id, category_id, slug, name, description, price_cents, image_url, tags, options, available, featured, sort_order) values ('item-sweet-plantains', 'cat-sides', 'sweet-plantains', 'Sweet Plantains', null, 500, null, '{"veg","gf"}', '[]'::jsonb, true, false, 30)
  on conflict (id) do update set name = excluded.name, description = excluded.description, price_cents = excluded.price_cents, image_url = excluded.image_url, tags = excluded.tags, options = excluded.options, featured = excluded.featured, sort_order = excluded.sort_order;
insert into public.menu_items (id, category_id, slug, name, description, price_cents, image_url, tags, options, available, featured, sort_order) values ('item-seaweed-salad', 'cat-sides', 'seaweed-salad', 'Seaweed Salad', null, 600, null, '{"veg"}', '[]'::jsonb, true, false, 31)
  on conflict (id) do update set name = excluded.name, description = excluded.description, price_cents = excluded.price_cents, image_url = excluded.image_url, tags = excluded.tags, options = excluded.options, featured = excluded.featured, sort_order = excluded.sort_order;
insert into public.menu_items (id, category_id, slug, name, description, price_cents, image_url, tags, options, available, featured, sort_order) values ('item-miso-soup', 'cat-sides', 'miso-soup', 'Miso Soup', null, 500, null, '{"veg"}', '[]'::jsonb, true, false, 32)
  on conflict (id) do update set name = excluded.name, description = excluded.description, price_cents = excluded.price_cents, image_url = excluded.image_url, tags = excluded.tags, options = excluded.options, featured = excluded.featured, sort_order = excluded.sort_order;
insert into public.menu_items (id, category_id, slug, name, description, price_cents, image_url, tags, options, available, featured, sort_order) values ('item-togarashi-fries', 'cat-sides', 'togarashi-fries', 'Togarashi Fries', 'Crispy fries, Japanese chili salt, spicy mayo.', 600, null, '{"veg"}', '[]'::jsonb, true, false, 33)
  on conflict (id) do update set name = excluded.name, description = excluded.description, price_cents = excluded.price_cents, image_url = excluded.image_url, tags = excluded.tags, options = excluded.options, featured = excluded.featured, sort_order = excluded.sort_order;
insert into public.menu_items (id, category_id, slug, name, description, price_cents, image_url, tags, options, available, featured, sort_order) values ('item-layover-lime-margarita', 'cat-drinks', 'layover-lime-margarita', 'Layover Lime Margarita', 'Classic lime, salt rim. First Class Mondays: 1 for $10, 2 for $15.', 1200, '/menu/marg_lime.jpg', '{"21+"}', '[]'::jsonb, true, false, 34)
  on conflict (id) do update set name = excluded.name, description = excluded.description, price_cents = excluded.price_cents, image_url = excluded.image_url, tags = excluded.tags, options = excluded.options, featured = excluded.featured, sort_order = excluded.sort_order;
insert into public.menu_items (id, category_id, slug, name, description, price_cents, image_url, tags, options, available, featured, sort_order) values ('item-golden-hour-margarita', 'cat-drinks', 'golden-hour-margarita', 'Golden Hour Margarita', 'Passion fruit and mango, sugar rim.', 1200, '/menu/marg_golden.jpg', '{"21+"}', '[]'::jsonb, true, false, 35)
  on conflict (id) do update set name = excluded.name, description = excluded.description, price_cents = excluded.price_cents, image_url = excluded.image_url, tags = excluded.tags, options = excluded.options, featured = excluded.featured, sort_order = excluded.sort_order;
insert into public.menu_items (id, category_id, slug, name, description, price_cents, image_url, tags, options, available, featured, sort_order) values ('item-berry-smooth-landing-margarita', 'cat-drinks', 'berry-smooth-landing-margarita', 'Berry Smooth Landing', 'Strawberry margarita, fresh berries.', 1200, '/menu/marg_berry.jpg', '{"21+"}', '[]'::jsonb, true, false, 36)
  on conflict (id) do update set name = excluded.name, description = excluded.description, price_cents = excluded.price_cents, image_url = excluded.image_url, tags = excluded.tags, options = excluded.options, featured = excluded.featured, sort_order = excluded.sort_order;
insert into public.menu_items (id, category_id, slug, name, description, price_cents, image_url, tags, options, available, featured, sort_order) values ('item-beer-bucket', 'cat-drinks', 'beer-bucket', 'Beer Bucket · 6', 'Six ice-cold beers. Thirsty Thursday: buy 5 get 1 free.', 2700, '/menu/beer_bucket.jpg', '{"21+"}', '[{"id":"beer","name":"Beer","required":true,"type":"single","choices":[{"id":"carib","name":"Carib"},{"id":"presidente","name":"Presidente"},{"id":"heineken","name":"Heineken","priceDeltaCents":300}]}]'::jsonb, true, false, 37)
  on conflict (id) do update set name = excluded.name, description = excluded.description, price_cents = excluded.price_cents, image_url = excluded.image_url, tags = excluded.tags, options = excluded.options, featured = excluded.featured, sort_order = excluded.sort_order;
insert into public.menu_items (id, category_id, slug, name, description, price_cents, image_url, tags, options, available, featured, sort_order) values ('item-rum-punch', 'cat-drinks', 'rum-punch', 'Route 86 Rum Punch', 'Island rum, passion fruit, nutmeg.', 900, null, '{"21+"}', '[]'::jsonb, true, false, 38)
  on conflict (id) do update set name = excluded.name, description = excluded.description, price_cents = excluded.price_cents, image_url = excluded.image_url, tags = excluded.tags, options = excluded.options, featured = excluded.featured, sort_order = excluded.sort_order;
insert into public.menu_items (id, category_id, slug, name, description, price_cents, image_url, tags, options, available, featured, sort_order) values ('item-sorrel-iced-tea', 'cat-drinks', 'sorrel-iced-tea', 'Sorrel Iced Tea', 'House-brewed, ginger, lime.', 400, null, '{"veg"}', '[]'::jsonb, true, false, 39)
  on conflict (id) do update set name = excluded.name, description = excluded.description, price_cents = excluded.price_cents, image_url = excluded.image_url, tags = excluded.tags, options = excluded.options, featured = excluded.featured, sort_order = excluded.sort_order;
insert into public.menu_items (id, category_id, slug, name, description, price_cents, image_url, tags, options, available, featured, sort_order) values ('item-soft-drink', 'cat-drinks', 'soft-drink', 'Soft Drink', 'Coke, Diet Coke, Sprite, Ting.', 300, null, '{}', '[]'::jsonb, true, false, 40)
  on conflict (id) do update set name = excluded.name, description = excluded.description, price_cents = excluded.price_cents, image_url = excluded.image_url, tags = excluded.tags, options = excluded.options, featured = excluded.featured, sort_order = excluded.sort_order;
insert into public.menu_items (id, category_id, slug, name, description, price_cents, image_url, tags, options, available, featured, sort_order) values ('item-bottled-water', 'cat-drinks', 'bottled-water', 'Bottled Water', null, 200, null, '{}', '[]'::jsonb, true, false, 41)
  on conflict (id) do update set name = excluded.name, description = excluded.description, price_cents = excluded.price_cents, image_url = excluded.image_url, tags = excluded.tags, options = excluded.options, featured = excluded.featured, sort_order = excluded.sort_order;
